language: node_js
node_js:
- 11.10.1
cache: yarn

before_script :
 - curl -o- -L https://yarnpkg.com/install.sh | bash -s
 - export PATH=$HOME/.yarn/bin:$PATH
 - yarn install

script:
  - yarn run build

deploy:
  provider: heroku
  api_key:
    secure: mAhBSCidpLVlx1bQI0gOi33jK4UOIyQZC0Vu9xFLThZzOuFrApPUsKtBxMYYM0PDVOyVhiCfpdx49cmVL7qAjqgfXJWJLJnFmdNg9vwgfMo6OC+UQqfzYT+n8LuMKSM9fzhNfScNAWroWOifXRus1knNBbZc1tGJHW/iqKfmxXpTgxgiKkd11HxuGqhXIdQabfop0IfYea5KIB9KUfOBvpT9x8ntI95T/IWunhdcBaw4/JzVRkvem3wq7omLYviE5qvtinDdKtwSB8188baE9RngUQUeUd+rizGZ5cddw/M7PfZibHimNch8g9y4sfdZ04kymDD9UN6CBRFNS+frt/zKOx/FpjLLvVf2pEK3IiApnsAu3bkXKA7BBBwXIXSGeUZpxz5sSiNyyIw366q7EMUguEfQlw3L/SEsmNY7Y2qbvY+SNzZnKwiM0fJI4nWGheSm8MNhQcJYuiOKwzfcv1tbEGoL2z6OZ2XsHvWzk67/gDQP7buEVL6HTjZ2wqeR6zFdfRyOgQDvGgN3yVlmDtfIqexttrajSHRUG140wI7p+SWuRU/5+kbFbE6T0Pfp1KhMbdDS/hIXR4UIaipLwu0qFfWcLiJrx6r5+XutpYv8rXkzRdEIIEpATpQZ3pFSqqMt/ow5O+PvKugghj26o5S8OvxAUTJpPKjFwjSCzDQ=
  app: 
    master: react-hn-clone